package com.attafitamim.file.picker.utils

// TODO may be this is redundant for ios. There is native method
object MimeTypeHelper {

    // https://gist.github.com/nimasdj/801b0b1a50112ea6a997#file-mimetypes-php
    private val mimeTypeMap = mapOf(
        "3dm" to listOf("x-world/x-3dmf"),
        "3dmf" to listOf("x-world/x-3dmf"),
        "3dml" to listOf("text/vnd.in3d.3dml"),
        "ds" to listOf("image/x-3ds"),
        "3g2" to listOf("video/3gpp2"),
        "3gp" to listOf("video/3gpp"),
        "7z" to listOf("application/x-7z-compressed"),
        "a" to listOf("application/octet-stream"),
        "aab" to listOf("application/x-authorware-bin"),
        "aac" to listOf("audio/x-aac"),
        "aam" to listOf("application/x-authorware-map"),
        "aas" to listOf("application/x-authorware-seg"),
        "abc" to listOf("text/vnd.abc"),
        "abw" to listOf("application/x-abiword"),
        "ac" to listOf("application/pkix-attr-cert"),
        "acc" to listOf("application/vnd.americandynamics.acc"),
        "ace" to listOf("application/x-ace-compressed"),
        "acgi" to listOf("text/html"),
        "acu" to listOf("application/vnd.acucobol"),
        "acutc" to listOf("application/vnd.acucorp"),
        "adp" to listOf("audio/adpcm"),
        "aep" to listOf("application/vnd.audiograph"),
        "afl" to listOf("video/animaflex"),
        "afm" to listOf("application/x-font-type1"),
        "afp" to listOf("application/vnd.ibm.modcap"),
        "ahead" to listOf("application/vnd.ahead.space"),
        "ai" to listOf("application/postscript"),
        "aif" to listOf("audio/aiff", "audio/x-aiff"),
        "aifc" to listOf("audio/aiff", "audio/x-aiff"),
        "aiff" to listOf("audio/aiff", "audio/x-aiff"),
        "aim" to listOf("application/x-aim"),
        "aip" to listOf("text/x-audiosoft-intra"),
        "air" to listOf("application/vnd.adobe.air-application-installer-package+zip"),
        "ait" to listOf("application/vnd.dvb.ait"),
        "ami" to listOf("application/vnd.amiga.ami"),
        "ani" to listOf("application/x-navi-animation"),
        "aos" to listOf("application/x-nokia-9000-communicator-add-on-software"),
        "apk" to listOf("application/vnd.android.package-archive"),
        "appcache" to listOf("text/cache-manifest"),
        "application" to listOf("application/x-ms-application"),
        "apr" to listOf("application/vnd.lotus-approach"),
        "aps" to listOf("application/mime"),
        "arc" to listOf("application/x-freearc"),
        "arj" to listOf("application/arj", "application/octet-stream"),
        "art" to listOf("image/x-jg"),
        "asc" to listOf("application/pgp-signature"),
        "asf" to listOf("video/x-ms-asf"),
        "asm" to listOf("text/x-asm"),
        "aso" to listOf("application/vnd.accpac.simply.aso"),
        "asp" to listOf("text/asp"),
        "asx" to listOf("application/x-mplayer2", "video/x-ms-asf", "video/x-ms-asf-plugin"),
        "atc" to listOf("application/vnd.acucorp"),
        "atom" to listOf("application/atom+xml"),
        "atomcat" to listOf("application/atomcat+xml"),
        "atomsvc" to listOf("application/atomsvc+xml"),
        "atx" to listOf("application/vnd.antix.game-component"),
        "au" to listOf("audio/basic"),
        "avi" to listOf(
            "application/x-troff-msvideo",
            "video/avi",
            "video/msvideo",
            "video/x-msvideo"
        ),
        "avs" to listOf("video/avs-video"),
        "aw" to listOf("application/applixware"),
        "azf" to listOf("application/vnd.airzip.filesecure.azf"),
        "azs" to listOf("application/vnd.airzip.filesecure.azs"),
        "azw" to listOf("application/vnd.amazon.ebook"),
        "bat" to listOf("application/x-msdownload"),
        "bcpio" to listOf("application/x-bcpio"),
        "bdf" to listOf("application/x-font-bdf"),
        "bdm" to listOf("application/vnd.syncml.dm+wbxml"),
        "bed" to listOf("application/vnd.realvnc.bed"),
        "bh2" to listOf("application/vnd.fujitsu.oasysprs"),
        "bin" to listOf(
            "application/mac-binary",
            "application/macbinary",
            "application/octet-stream",
            "application/x-binary",
            "application/x-macbinary"
        ),
        "blb" to listOf("application/x-blorb"),
        "blorb" to listOf("application/x-blorb"),
        "bm" to listOf("image/bmp"),
        "bmi" to listOf("application/vnd.bmi"),
        "bmp" to listOf("image/bmp", "image/x-windows-bmp"),
        "boo" to listOf("application/book"),
        "book" to listOf("application/vnd.framemaker"),
        "box" to listOf("application/vnd.previewsystems.box"),
        "boz" to listOf("application/x-bzip2"),
        "bpk" to listOf("application/octet-stream"),
        "bsh" to listOf("application/x-bsh"),
        "btif" to listOf("image/prs.btif"),
        "buffer" to listOf("application/octet-stream"),
        "bz" to listOf("application/x-bzip"),
        "bz2" to listOf("application/x-bzip2"),
        "c" to listOf("text/x-c"),
        "c++" to listOf("text/plain"),
        "c11amc" to listOf("application/vnd.cluetrust.cartomobile-config"),
        "c11amz" to listOf("application/vnd.cluetrust.cartomobile-config-pkg"),
        "c4d" to listOf("application/vnd.clonk.c4group"),
        "c4f" to listOf("application/vnd.clonk.c4group"),
        "c4g" to listOf("application/vnd.clonk.c4group"),
        "c4p" to listOf("application/vnd.clonk.c4group"),
        "c4u" to listOf("application/vnd.clonk.c4group"),
        "cab" to listOf("application/vnd.ms-cab-compressed"),
        "caf" to listOf("audio/x-caf"),
        "cap" to listOf("application/vnd.tcpdump.pcap"),
        "car" to listOf("application/vnd.curl.car"),
        "cat" to listOf("application/vnd.ms-pki.seccat"),
        "cb7" to listOf("application/x-cbr"),
        "cba" to listOf("application/x-cbr"),
        "cbr" to listOf("application/x-cbr"),
        "cbt" to listOf("application/x-cbr"),
        "cbz" to listOf("application/x-cbr"),
        "cc" to listOf("text/plain", "text/x-c"),
        "ccad" to listOf("application/clariscad"),
        "cco" to listOf("application/x-cocoa"),
        "cct" to listOf("application/x-director"),
        "ccxml" to listOf("application/ccxml+xml"),
        "cdbcmsg" to listOf("application/vnd.contact.cmsg"),
        "cdf" to listOf("application/cdf", "application/x-cdf", "application/x-netcdf"),
        "cdkey" to listOf("application/vnd.mediastation.cdkey"),
        "cdmia" to listOf("application/cdmi-capability"),
        "cdmic" to listOf("application/cdmi-container"),
        "cdmid" to listOf("application/cdmi-domain"),
        "cdmio" to listOf("application/cdmi-object"),
        "cdmiq" to listOf("application/cdmi-queue"),
        "cdx" to listOf("chemical/x-cdx"),
        "cdxml" to listOf("application/vnd.chemdraw+xml"),
        "cdy" to listOf("application/vnd.cinderella"),
        "cer" to listOf("application/pkix-cert", "application/x-x509-ca-cert"),
        "cfs" to listOf("application/x-cfs-compressed"),
        "cgm" to listOf("image/cgm"),
        "cha" to listOf("application/x-chat"),
        "chat" to listOf("application/x-chat"),
        "chm" to listOf("application/vnd.ms-htmlhelp"),
        "chrt" to listOf("application/vnd.kde.kchart"),
        "cif" to listOf("chemical/x-cif"),
        "cii" to listOf("application/vnd.anser-web-certificate-issue-initiation"),
        "cil" to listOf("application/vnd.ms-artgalry"),
        "cla" to listOf("application/vnd.claymore"),
        "class" to listOf(
            "application/java",
            "application/java-byte-code",
            "application/x-java-class"
        ),
        "clkk" to listOf("application/vnd.crick.clicker.keyboard"),
        "clkp" to listOf("application/vnd.crick.clicker.palette"),
        "clkt" to listOf("application/vnd.crick.clicker.template"),
        "clkw" to listOf("application/vnd.crick.clicker.wordbank"),
        "clkx" to listOf("application/vnd.crick.clicker"),
        "clp" to listOf("application/x-msclip"),
        "cmc" to listOf("application/vnd.cosmocaller"),
        "cmdf" to listOf("chemical/x-cmdf"),
        "cml" to listOf("chemical/x-cml"),
        "cmp" to listOf("application/vnd.yellowriver-custom-menu"),
        "cmx" to listOf("image/x-cmx"),
        "cod" to listOf("application/vnd.rim.cod"),
        "com" to listOf("application/octet-stream", "text/plain"),
        "conf" to listOf("text/plain"),
        "cpio" to listOf("application/x-cpio"),
        "cpp" to listOf("text/x-c"),
        "cpt" to listOf("application/x-compactpro", "application/x-cpt"),
        "crd" to listOf("application/x-mscardfile"),
        "crl" to listOf("application/pkcs-crl", "application/pkix-crl"),
        "crt" to listOf(
            "application/pkix-cert",
            "application/x-x509-ca-cert",
            "application/x-x509-user-cert"
        ),
        "crx" to listOf("application/x-chrome-extension"),
        "cryptonote" to listOf("application/vnd.rig.cryptonote"),
        "csh" to listOf("application/x-csh", "text/x-script.csh"),
        "csml" to listOf("chemical/x-csml"),
        "csp" to listOf("application/vnd.commonspace"),
        "css" to listOf("application/x-pointplus", "text/css"),
        "cst" to listOf("application/x-director"),
        "csv" to listOf("text/csv"),
        "cu" to listOf("application/cu-seeme"),
        "curl" to listOf("text/vnd.curl"),
        "cww" to listOf("application/prs.cww"),
        "cxt" to listOf("application/x-director"),
        "cxx" to listOf("text/x-c"),
        "dae" to listOf("model/vnd.collada+xml"),
        "daf" to listOf("application/vnd.mobius.daf"),
        "dart" to listOf("application/vnd.dart"),
        "dataless" to listOf("application/vnd.fdsn.seed"),
        "davmount" to listOf("application/davmount+xml"),
        "dbk" to listOf("application/docbook+xml"),
        "dcr" to listOf("application/x-director"),
        "dcurl" to listOf("text/vnd.curl.dcurl"),
        "dd2" to listOf("application/vnd.oma.dd2+xml"),
        "ddd" to listOf("application/vnd.fujixerox.ddd"),
        "deb" to listOf("application/x-debian-package"),
        "deepv" to listOf("application/x-deepv"),
        "def" to listOf("text/plain"),
        "deploy" to listOf("application/octet-stream"),
        "der" to listOf("application/x-x509-ca-cert"),
        "dfac" to listOf("application/vnd.dreamfactory"),
        "dgc" to listOf("application/x-dgc-compressed"),
        "dic" to listOf("text/x-c"),
        "dif" to listOf("video/x-dv"),
        "diff" to listOf("text/plain"),
        "dir" to listOf("application/x-director"),
        "dis" to listOf("application/vnd.mobius.dis"),
        "dist" to listOf("application/octet-stream"),
        "distz" to listOf("application/octet-stream"),
        "djv" to listOf("image/vnd.djvu"),
        "djvu" to listOf("image/vnd.djvu"),
        "dl" to listOf("video/dl", "video/x-dl"),
        "dll" to listOf("application/x-msdownload"),
        "dmg" to listOf("application/x-apple-diskimage"),
        "dmp" to listOf("application/vnd.tcpdump.pcap"),
        "dms" to listOf("application/octet-stream"),
        "dna" to listOf("application/vnd.dna"),
        "doc" to listOf("application/msword"),
        "docm" to listOf("application/vnd.ms-word.document.macroenabled.12"),
        "docx" to listOf("application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
        "dot" to listOf("application/msword"),
        "dotm" to listOf("application/vnd.ms-word.template.macroenabled.12"),
        "dotx" to listOf("application/vnd.openxmlformats-officedocument.wordprocessingml.template"),
        "dp" to listOf("application/vnd.osgi.dp"),
        "dpg" to listOf("application/vnd.dpgraph"),
        "dra" to listOf("audio/vnd.dra"),
        "drw" to listOf("application/drafting"),
        "dsc" to listOf("text/prs.lines.tag"),
        "dssc" to listOf("application/dssc+der"),
        "dtb" to listOf("application/x-dtbook+xml"),
        "dtd" to listOf("application/xml-dtd"),
        "dts" to listOf("audio/vnd.dts"),
        "dtshd" to listOf("audio/vnd.dts.hd"),
        "dump" to listOf("application/octet-stream"),
        "dv" to listOf("video/x-dv"),
        "dvb" to listOf("video/vnd.dvb.file"),
        "dvi" to listOf("application/x-dvi"),
        "dwf" to listOf("drawing/x-dwf (old)", "model/vnd.dwf"),
        "dwg" to listOf("application/acad", "image/vnd.dwg", "image/x-dwg"),
        "dxf" to listOf("image/vnd.dxf"),
        "dxp" to listOf("application/vnd.spotfire.dxp"),
        "dxr" to listOf("application/x-director"),
        "ecelp4800" to listOf("audio/vnd.nuera.ecelp4800"),
        "ecelp7470" to listOf("audio/vnd.nuera.ecelp7470"),
        "ecelp9600" to listOf("audio/vnd.nuera.ecelp9600"),
        "ecma" to listOf("application/ecmascript"),
        "edm" to listOf("application/vnd.novadigm.edm"),
        "edx" to listOf("application/vnd.novadigm.edx"),
        "efif" to listOf("application/vnd.picsel"),
        "ei6" to listOf("application/vnd.pg.osasli"),
        "el" to listOf("text/x-script.elisp"),
        "elc" to listOf("application/x-bytecode.elisp (compiled elisp)", "application/x-elc"),
        "emf" to listOf("application/x-msmetafile"),
        "eml" to listOf("message/rfc822"),
        "emma" to listOf("application/emma+xml"),
        "emz" to listOf("application/x-msmetafile"),
        "env" to listOf("application/x-envoy"),
        "eol" to listOf("audio/vnd.digital-winds"),
        "eot" to listOf("application/vnd.ms-fontobject"),
        "eps" to listOf("application/postscript"),
        "epub" to listOf("application/epub+zip"),
        "es" to listOf("application/x-esrehber"),
        "es3" to listOf("application/vnd.eszigno3+xml"),
        "esa" to listOf("application/vnd.osgi.subsystem"),
        "esf" to listOf("application/vnd.epson.esf"),
        "et3" to listOf("application/vnd.eszigno3+xml"),
        "etx" to listOf("text/x-setext"),
        "eva" to listOf("application/x-eva"),
        "event-stream" to listOf("text/event-stream"),
        "evy" to listOf("application/envoy", "application/x-envoy"),
        "exe" to listOf("application/x-msdownload", "application/x-dosexec"),
        "exi" to listOf("application/exi"),
        "ext" to listOf("application/vnd.novadigm.ext"),
        "ez" to listOf("application/andrew-inset"),
        "ez2" to listOf("application/vnd.ezpix-album"),
        "ez3" to listOf("application/vnd.ezpix-package"),
        "f" to listOf("text/plain", "text/x-fortran"),
        "f4v" to listOf("video/x-f4v"),
        "f77" to listOf("text/x-fortran"),
        "f90" to listOf("text/plain", "text/x-fortran"),
        "fbs" to listOf("image/vnd.fastbidsheet"),
        "fcdt" to listOf("application/vnd.adobe.formscentral.fcdt"),
        "fcs" to listOf("application/vnd.isac.fcs"),
        "fdf" to listOf("application/vnd.fdf"),
        "fe_launch" to listOf("application/vnd.denovo.fcselayout-link"),
        "fg5" to listOf("application/vnd.fujitsu.oasysgp"),
        "fgd" to listOf("application/x-director"),
        "fh" to listOf("image/x-freehand"),
        "fh4" to listOf("image/x-freehand"),
        "fh5" to listOf("image/x-freehand"),
        "fh7" to listOf("image/x-freehand"),
        "fhc" to listOf("image/x-freehand"),
        "fif" to listOf("application/fractals", "image/fif"),
        "fig" to listOf("application/x-xfig"),
        "flac" to listOf("audio/flac"),
        "fli" to listOf("video/fli", "video/x-fli"),
        "flo" to listOf("application/vnd.micrografx.flo"),
        "flv" to listOf("video/x-flv"),
        "flw" to listOf("application/vnd.kde.kivio"),
        "flx" to listOf("text/vnd.fmi.flexstor"),
        "fly" to listOf("text/vnd.fly"),
        "fm" to listOf("application/vnd.framemaker"),
        "fmf" to listOf("video/x-atomic3d-feature"),
        "fnc" to listOf("application/vnd.frogans.fnc"),
        "for" to listOf("text/plain", "text/x-fortran"),
        "fpx" to listOf("image/vnd.fpx", "image/vnd.net-fpx"),
        "frame" to listOf("application/vnd.framemaker"),
        "frl" to listOf("application/freeloader"),
        "fsc" to listOf("application/vnd.fsc.weblaunch"),
        "fst" to listOf("image/vnd.fst"),
        "ftc" to listOf("application/vnd.fluxtime.clip"),
        "fti" to listOf("application/vnd.anser-web-funds-transfer-initiation"),
        "funk" to listOf("audio/make"),
        "fvt" to listOf("video/vnd.fvt"),
        "fxp" to listOf("application/vnd.adobe.fxp"),
        "fxpl" to listOf("application/vnd.adobe.fxp"),
        "fzs" to listOf("application/vnd.fuzzysheet"),
        "g" to listOf("text/plain"),
        "g2w" to listOf("application/vnd.geoplan"),
        "g3" to listOf("image/g3fax"),
        "g3w" to listOf("application/vnd.geospace"),
        "gac" to listOf("application/vnd.groove-account"),
        "gam" to listOf("application/x-tads"),
        "gbr" to listOf("application/rpki-ghostbusters"),
        "gca" to listOf("application/x-gca-compressed"),
        "gdl" to listOf("model/vnd.gdl"),
        "geo" to listOf("application/vnd.dynageo"),
        "gex" to listOf("application/vnd.geometry-explorer"),
        "ggb" to listOf("application/vnd.geogebra.file"),
        "ggt" to listOf("application/vnd.geogebra.tool"),
        "ghf" to listOf("application/vnd.groove-help"),
        "gif" to listOf("image/gif"),
        "gim" to listOf("application/vnd.groove-identity-message"),
        "gl" to listOf("video/gl", "video/x-gl"),
        "gml" to listOf("application/gml+xml"),
        "gmx" to listOf("application/vnd.gmx"),
        "gnumeric" to listOf("application/x-gnumeric"),
        "gph" to listOf("application/vnd.flographit"),
        "gpx" to listOf("application/gpx+xml"),
        "gqf" to listOf("application/vnd.grafeq"),
        "gqs" to listOf("application/vnd.grafeq"),
        "gram" to listOf("application/srgs"),
        "gramps" to listOf("application/x-gramps-xml"),
        "gre" to listOf("application/vnd.geometry-explorer"),
        "grv" to listOf("application/vnd.groove-injector"),
        "grxml" to listOf("application/srgs+xml"),
        "gsd" to listOf("audio/x-gsm"),
        "gsf" to listOf("application/x-font-ghostscript"),
        "gsm" to listOf("audio/x-gsm"),
        "gsp" to listOf("application/x-gsp"),
        "gss" to listOf("application/x-gss"),
        "gtar" to listOf("application/x-gtar"),
        "gtm" to listOf("application/vnd.groove-tool-message"),
        "gtw" to listOf("model/vnd.gtw"),
        "gv" to listOf("text/vnd.graphviz"),
        "gxf" to listOf("application/gxf"),
        "gxt" to listOf("application/vnd.geonext"),
        "gz" to listOf("application/x-compressed", "application/x-gzip"),
        "gzip" to listOf("application/x-gzip", "multipart/x-gzip"),
        "h" to listOf("text/plain", "text/x-h"),
        "h261" to listOf("video/h261"),
        "h263" to listOf("video/h263"),
        "h264" to listOf("video/h264"),
        "hal" to listOf("application/vnd.hal+xml"),
        "hbci" to listOf("application/vnd.hbci"),
        "hdf" to listOf("application/x-hdf"),
        "help" to listOf("application/x-helpfile"),
        "hgl" to listOf("application/vnd.hp-hpgl"),
        "hh" to listOf("text/plain", "text/x-h"),
        "hlb" to listOf("text/x-script"),
        "hlp" to listOf("application/hlp", "application/x-helpfile", "application/x-winhelp"),
        "hpg" to listOf("application/vnd.hp-hpgl"),
        "hpgl" to listOf("application/vnd.hp-hpgl"),
        "hpid" to listOf("application/vnd.hp-hpid"),
        "hps" to listOf("application/vnd.hp-hps"),
        "hqx" to listOf(
            "application/binhex",
            "application/binhex4",
            "application/mac-binhex",
            "application/mac-binhex40",
            "application/x-binhex40",
            "application/x-mac-binhex40"
        ),
        "hta" to listOf("application/hta"),
        "htc" to listOf("text/x-component"),
        "htke" to listOf("application/vnd.kenameaapp"),
        "htm" to listOf("text/html"),
        "html" to listOf("text/html"),
        "htmls" to listOf("text/html"),
        "htt" to listOf("text/webviewhtml"),
        "htx" to listOf("text/html"),
        "hvd" to listOf("application/vnd.yamaha.hv-dic"),
        "hvp" to listOf("application/vnd.yamaha.hv-voice"),
        "hvs" to listOf("application/vnd.yamaha.hv-script"),
        "i2g" to listOf("application/vnd.intergeo"),
        "icc" to listOf("application/vnd.iccprofile"),
        "ice" to listOf("x-conference/x-cooltalk"),
        "icm" to listOf("application/vnd.iccprofile"),
        "ico" to listOf("image/x-icon"),
        "ics" to listOf("text/calendar"),
        "idc" to listOf("text/plain"),
        "ief" to listOf("image/ief"),
        "iefs" to listOf("image/ief"),
        "ifb" to listOf("text/calendar"),
        "ifm" to listOf("application/vnd.shana.informed.formdata"),
        "iges" to listOf("application/iges", "model/iges"),
        "igl" to listOf("application/vnd.igloader"),
        "igm" to listOf("application/vnd.insors.igm"),
        "igs" to listOf("application/iges", "model/iges"),
        "igx" to listOf("application/vnd.micrografx.igx"),
        "iif" to listOf("application/vnd.shana.informed.interchange"),
        "ima" to listOf("application/x-ima"),
        "imap" to listOf("application/x-httpd-imap"),
        "imp" to listOf("application/vnd.accpac.simply.imp"),
        "ims" to listOf("application/vnd.ms-ims"),
        "in" to listOf("text/plain"),
        "inf" to listOf("application/inf"),
        "ink" to listOf("application/inkml+xml"),
        "inkml" to listOf("application/inkml+xml"),
        "ins" to listOf("application/x-internett-signup"),
        "install" to listOf("application/x-install-instructions"),
        "iota" to listOf("application/vnd.astraea-software.iota"),
        "ip" to listOf("application/x-ip2"),
        "ipfix" to listOf("application/ipfix"),
        "ipk" to listOf("application/vnd.shana.informed.package"),
        "irm" to listOf("application/vnd.ibm.rights-management"),
        "irp" to listOf("application/vnd.irepository.package+xml"),
        "iso" to listOf("application/x-iso9660-image"),
        "isu" to listOf("video/x-isvideo"),
        "it" to listOf("audio/it"),
        "itp" to listOf("application/vnd.shana.informed.formtemplate"),
        "iv" to listOf("application/x-inventor"),
        "ivp" to listOf("application/vnd.immervision-ivp"),
        "ivr" to listOf("i-world/i-vrml"),
        "ivu" to listOf("application/vnd.immervision-ivu"),
        "ivy" to listOf("application/x-livescreen"),
        "jad" to listOf("text/vnd.sun.j2me.app-descriptor"),
        "jam" to listOf("application/vnd.jam"),
        "jar" to listOf("application/java-archive"),
        "jav" to listOf("text/plain", "text/x-java-source"),
        "java" to listOf("text/plain", "text/x-java-source"),
        "jcm" to listOf("application/x-java-commerce"),
        "jfif" to listOf("image/jpeg", "image/pjpeg"),
        "jfif-tbnl" to listOf("image/jpeg"),
        "jisp" to listOf("application/vnd.jisp"),
        "jlt" to listOf("application/vnd.hp-jlyt"),
        "jnlp" to listOf("application/x-java-jnlp-file"),
        "joda" to listOf("application/vnd.joost.joda-archive"),
        "jpe" to listOf("image/jpeg", "image/pjpeg"),
        "jpeg" to listOf("image/jpeg", "image/pjpeg"),
        "jpg" to listOf("image/jpeg", "image/pjpeg"),
        "jpgm" to listOf("video/jpm"),
        "jpgv" to listOf("video/jpeg"),
        "jpm" to listOf("video/jpm"),
        "jps" to listOf("image/x-jps"),
        "js" to listOf("application/javascript"),
        "json" to listOf("application/json", "text/plain"),
        "jsonml" to listOf("application/jsonml+json"),
        "jut" to listOf("image/jutvision"),
        "kar" to listOf("audio/midi", "music/x-karaoke"),
        "karbon" to listOf("application/vnd.kde.karbon"),
        "kfo" to listOf("application/vnd.kde.kformula"),
        "kia" to listOf("application/vnd.kidspiration"),
        "kil" to listOf("application/x-killustrator"),
        "kml" to listOf("application/vnd.google-earth.kml+xml"),
        "kmz" to listOf("application/vnd.google-earth.kmz"),
        "kne" to listOf("application/vnd.kinar"),
        "knp" to listOf("application/vnd.kinar"),
        "kon" to listOf("application/vnd.kde.kontour"),
        "kpr" to listOf("application/vnd.kde.kpresenter"),
        "kpt" to listOf("application/vnd.kde.kpresenter"),
        "kpxx" to listOf("application/vnd.ds-keypoint"),
        "ksh" to listOf("application/x-ksh", "text/x-script.ksh"),
        "ksp" to listOf("application/vnd.kde.kspread"),
        "ktr" to listOf("application/vnd.kahootz"),
        "ktx" to listOf("image/ktx"),
        "ktz" to listOf("application/vnd.kahootz"),
        "kwd" to listOf("application/vnd.kde.kword"),
        "kwt" to listOf("application/vnd.kde.kword"),
        "la" to listOf("audio/nspaudio", "audio/x-nspaudio"),
        "lam" to listOf("audio/x-liveaudio"),
        "lasxml" to listOf("application/vnd.las.las+xml"),
        "latex" to listOf("application/x-latex"),
        "lbd" to listOf("application/vnd.llamagraphics.life-balance.desktop"),
        "lbe" to listOf("application/vnd.llamagraphics.life-balance.exchange+xml"),
        "les" to listOf("application/vnd.hhe.lesson-player"),
        "lha" to listOf("application/lha", "application/octet-stream", "application/x-lha"),
        "lhx" to listOf("application/octet-stream"),
        "link66" to listOf("application/vnd.route66.link66+xml"),
        "list" to listOf("text/plain"),
        "list3820" to listOf("application/vnd.ibm.modcap"),
        "listafp" to listOf("application/vnd.ibm.modcap"),
        "lma" to listOf("audio/nspaudio", "audio/x-nspaudio"),
        "lnk" to listOf("application/x-ms-shortcut"),
        "log" to listOf("text/plain"),
        "lostxml" to listOf("application/lost+xml"),
        "lrf" to listOf("application/octet-stream"),
        "lrm" to listOf("application/vnd.ms-lrm"),
        "lsp" to listOf("application/x-lisp", "text/x-script.lisp"),
        "lst" to listOf("text/plain"),
        "lsx" to listOf("text/x-la-asf"),
        "ltf" to listOf("application/vnd.frogans.ltf"),
        "ltx" to listOf("application/x-latex"),
        "lua" to listOf("text/x-lua"),
        "luac" to listOf("application/x-lua-bytecode"),
        "lvp" to listOf("audio/vnd.lucent.voice"),
        "lwp" to listOf("application/vnd.lotus-wordpro"),
        "lzh" to listOf("application/octet-stream", "application/x-lzh"),
        "lzx" to listOf("application/lzx", "application/octet-stream", "application/x-lzx"),
        "m" to listOf("text/plain", "text/x-m"),
        "m13" to listOf("application/x-msmediaview"),
        "m14" to listOf("application/x-msmediaview"),
        "m1v" to listOf("video/mpeg"),
        "m21" to listOf("application/mp21"),
        "m2a" to listOf("audio/mpeg"),
        "m2v" to listOf("video/mpeg"),
        "m3a" to listOf("audio/mpeg"),
        "m3u" to listOf("audio/x-mpegurl"),
        "m3u8" to listOf("application/x-mpegURL"),
        "m4a" to listOf("audio/mp4"),
        "m4p" to listOf("application/mp4"),
        "m4u" to listOf("video/vnd.mpegurl"),
        "m4v" to listOf("video/x-m4v"),
        "ma" to listOf("application/mathematica"),
        "mads" to listOf("application/mads+xml"),
        "mag" to listOf("application/vnd.ecowin.chart"),
        "maker" to listOf("application/vnd.framemaker"),
        "man" to listOf("text/troff"),
        "manifest" to listOf("text/cache-manifest"),
        "map" to listOf("application/x-navimap"),
        "mar" to listOf("application/octet-stream"),
        "markdown" to listOf("text/x-markdown"),
        "mathml" to listOf("application/mathml+xml"),
        "mb" to listOf("application/mathematica"),
        "mbd" to listOf("application/mbedlet"),
        "mbk" to listOf("application/vnd.mobius.mbk"),
        "mbox" to listOf("application/mbox"),
        "mc" to listOf("application/x-magic-cap-package-1.0"),
        "mc1" to listOf("application/vnd.medcalcdata"),
        "mcd" to listOf("application/mcad", "application/x-mathcad"),
        "mcf" to listOf("image/vasa", "text/mcf"),
        "mcp" to listOf("application/netmc"),
        "mcurl" to listOf("text/vnd.curl.mcurl"),
        "md" to listOf("text/x-markdown"),
        "mdb" to listOf("application/x-msaccess"),
        "mdi" to listOf("image/vnd.ms-modi"),
        "me" to listOf("text/troff"),
        "mesh" to listOf("model/mesh"),
        "meta4" to listOf("application/metalink4+xml"),
        "metalink" to listOf("application/metalink+xml"),
        "mets" to listOf("application/mets+xml"),
        "mfm" to listOf("application/vnd.mfmp"),
        "mft" to listOf("application/rpki-manifest"),
        "mgp" to listOf("application/vnd.osgeo.mapguide.package"),
        "mgz" to listOf("application/vnd.proteus.magazine"),
        "mht" to listOf("message/rfc822"),
        "mhtml" to listOf("message/rfc822"),
        "mid" to listOf(
            "application/x-midi",
            "audio/midi",
            "audio/x-mid",
            "audio/x-midi",
            "music/crescendo",
            "x-music/x-midi"
        ),
        "midi" to listOf(
            "application/x-midi",
            "audio/midi",
            "audio/x-mid",
            "audio/x-midi",
            "music/crescendo",
            "x-music/x-midi"
        ),
        "mie" to listOf("application/x-mie"),
        "mif" to listOf("application/x-frame", "application/x-mif"),
        "mime" to listOf("message/rfc822", "www/mime"),
        "mj2" to listOf("video/mj2"),
        "mjf" to listOf("audio/x-vnd.audioexplosion.mjuicemediafile"),
        "mjp2" to listOf("video/mj2"),
        "mjpg" to listOf("video/x-motion-jpeg"),
        "mk3d" to listOf("video/x-matroska"),
        "mka" to listOf("audio/x-matroska"),
        "mkd" to listOf("text/x-markdown"),
        "mks" to listOf("video/x-matroska"),
        "mkv" to listOf("video/x-matroska"),
        "mlp" to listOf("application/vnd.dolby.mlp"),
        "mm" to listOf("application/base64", "application/x-meme"),
        "mmd" to listOf("application/vnd.chipnuts.karaoke-mmd"),
        "mme" to listOf("application/base64"),
        "mmf" to listOf("application/vnd.smaf"),
        "mmr" to listOf("image/vnd.fujixerox.edmics-mmr"),
        "mng" to listOf("video/x-mng"),
        "mny" to listOf("application/x-msmoney"),
        "mobi" to listOf("application/x-mobipocket-ebook"),
        "mod" to listOf("audio/mod", "audio/x-mod"),
        "mods" to listOf("application/mods+xml"),
        "moov" to listOf("video/quicktime"),
        "mov" to listOf("video/quicktime"),
        "movie" to listOf("video/x-sgi-movie"),
        "mp2" to listOf(
            "audio/mpeg",
            "audio/x-mpeg",
            "video/mpeg",
            "video/x-mpeg",
            "video/x-mpeq2a"
        ),
        "mp21" to listOf("application/mp21"),
        "mp2a" to listOf("audio/mpeg"),
        "mp3" to listOf("audio/mpeg3", "audio/x-mpeg-3", "video/mpeg", "video/x-mpeg"),
        "mp4" to listOf("video/mp4"),
        "mp4a" to listOf("audio/mp4"),
        "mp4s" to listOf("application/mp4"),
        "mp4v" to listOf("video/mp4"),
        "mpa" to listOf("audio/mpeg", "video/mpeg"),
        "mpc" to listOf("application/vnd.mophun.certificate"),
        "mpe" to listOf("video/mpeg"),
        "mpeg" to listOf("video/mpeg"),
        "mpg" to listOf("audio/mpeg", "video/mpeg"),
        "mpg4" to listOf("video/mp4"),
        "mpga" to listOf("audio/mpeg"),
        "mpkg" to listOf("application/vnd.apple.installer+xml"),
        "mpm" to listOf("application/vnd.blueice.multipass"),
        "mpn" to listOf("application/vnd.mophun.application"),
        "mpp" to listOf("application/vnd.ms-project"),
        "mpt" to listOf("application/vnd.ms-project"),
        "mpv" to listOf("application/x-project"),
        "mpx" to listOf("application/x-project"),
        "mpy" to listOf("application/vnd.ibm.minipay"),
        "mqy" to listOf("application/vnd.mobius.mqy"),
        "mrc" to listOf("application/marc"),
        "mrcx" to listOf("application/marcxml+xml"),
        "ms" to listOf("text/troff"),
        "mscml" to listOf("application/mediaservercontrol+xml"),
        "mseed" to listOf("application/vnd.fdsn.mseed"),
        "mseq" to listOf("application/vnd.mseq"),
        "msf" to listOf("application/vnd.epson.msf"),
        "msh" to listOf("model/mesh"),
        "msi" to listOf("application/x-msdownload"),
        "msl" to listOf("application/vnd.mobius.msl"),
        "msty" to listOf("application/vnd.muvee.style"),
        "mts" to listOf("model/vnd.mts"),
        "mus" to listOf("application/vnd.musician"),
        "musicxml" to listOf("application/vnd.recordare.musicxml+xml"),
        "mv" to listOf("video/x-sgi-movie"),
        "mvb" to listOf("application/x-msmediaview"),
        "mwf" to listOf("application/vnd.mfer"),
        "mxf" to listOf("application/mxf"),
        "mxl" to listOf("application/vnd.recordare.musicxml"),
        "mxml" to listOf("application/xv+xml"),
        "mxs" to listOf("application/vnd.triscape.mxs"),
        "mxu" to listOf("video/vnd.mpegurl"),
        "my" to listOf("audio/make"),
        "mzz" to listOf("application/x-vnd.audioexplosion.mzz"),
        "n-gage" to listOf("application/vnd.nokia.n-gage.symbian.install"),
        "n3" to listOf("text/n3"),
        "nap" to listOf("image/naplps"),
        "naplps" to listOf("image/naplps"),
        "nb" to listOf("application/mathematica"),
        "nbp" to listOf("application/vnd.wolfram.player"),
        "nc" to listOf("application/x-netcdf"),
        "ncm" to listOf("application/vnd.nokia.configuration-message"),
        "ncx" to listOf("application/x-dtbncx+xml"),
        "nfo" to listOf("text/x-nfo"),
        "ngdat" to listOf("application/vnd.nokia.n-gage.data"),
        "nif" to listOf("image/x-niff"),
        "niff" to listOf("image/x-niff"),
        "nitf" to listOf("application/vnd.nitf"),
        "nix" to listOf("application/x-mix-transfer"),
        "nlu" to listOf("application/vnd.neurolanguage.nlu"),
        "nml" to listOf("application/vnd.enliven"),
        "nnd" to listOf("application/vnd.noblenet-directory"),
        "nns" to listOf("application/vnd.noblenet-sealer"),
        "nnw" to listOf("application/vnd.noblenet-web"),
        "npx" to listOf("image/vnd.net-fpx"),
        "nsc" to listOf("application/x-conference"),
        "nsf" to listOf("application/vnd.lotus-notes"),
        "ntf" to listOf("application/vnd.nitf"),
        "nvd" to listOf("application/x-navidoc"),
        "nws" to listOf("message/rfc822"),
        "nzb" to listOf("application/x-nzb"),
        "o" to listOf("application/octet-stream"),
        "oa2" to listOf("application/vnd.fujitsu.oasys2"),
        "oa3" to listOf("application/vnd.fujitsu.oasys3"),
        "oas" to listOf("application/vnd.fujitsu.oasys"),
        "obd" to listOf("application/x-msbinder"),
        "obj" to listOf("application/x-tgif"),
        "oda" to listOf("application/oda"),
        "odb" to listOf("application/vnd.oasis.opendocument.database"),
        "odc" to listOf("application/vnd.oasis.opendocument.chart"),
        "odf" to listOf("application/vnd.oasis.opendocument.formula"),
        "odft" to listOf("application/vnd.oasis.opendocument.formula-template"),
        "odg" to listOf("application/vnd.oasis.opendocument.graphics"),
        "odi" to listOf("application/vnd.oasis.opendocument.image"),
        "odm" to listOf("application/vnd.oasis.opendocument.text-master"),
        "odp" to listOf("application/vnd.oasis.opendocument.presentation"),
        "ods" to listOf("application/vnd.oasis.opendocument.spreadsheet"),
        "odt" to listOf("application/vnd.oasis.opendocument.text"),
        "oga" to listOf("audio/ogg"),
        "ogg" to listOf("audio/ogg"),
        "ogv" to listOf("video/ogg"),
        "ogx" to listOf("application/ogg"),
        "omc" to listOf("application/x-omc"),
        "omcd" to listOf("application/x-omcdatamaker"),
        "omcr" to listOf("application/x-omcregerator"),
        "omdoc" to listOf("application/omdoc+xml"),
        "onepkg" to listOf("application/onenote"),
        "onetmp" to listOf("application/onenote"),
        "onetoc" to listOf("application/onenote"),
        "onetoc2" to listOf("application/onenote"),
        "opf" to listOf("application/oebps-package+xml"),
        "opml" to listOf("text/x-opml"),
        "oprc" to listOf("application/vnd.palm"),
        "org" to listOf("application/vnd.lotus-organizer"),
        "osf" to listOf("application/vnd.yamaha.openscoreformat"),
        "osfpvg" to listOf("application/vnd.yamaha.openscoreformat.osfpvg+xml"),
        "otc" to listOf("application/vnd.oasis.opendocument.chart-template"),
        "otf" to listOf("font/opentype"),
        "otg" to listOf("application/vnd.oasis.opendocument.graphics-template"),
        "oth" to listOf("application/vnd.oasis.opendocument.text-web"),
        "oti" to listOf("application/vnd.oasis.opendocument.image-template"),
        "otm" to listOf("application/vnd.oasis.opendocument.text-master"),
        "otp" to listOf("application/vnd.oasis.opendocument.presentation-template"),
        "ots" to listOf("application/vnd.oasis.opendocument.spreadsheet-template"),
        "ott" to listOf("application/vnd.oasis.opendocument.text-template"),
        "oxps" to listOf("application/oxps"),
        "oxt" to listOf("application/vnd.openofficeorg.extension"),
        "p" to listOf("text/x-pascal"),
        "p10" to listOf("application/pkcs10", "application/x-pkcs10"),
        "p12" to listOf("application/pkcs-12", "application/x-pkcs12"),
        "p7a" to listOf("application/x-pkcs7-signature"),
        "p7b" to listOf("application/x-pkcs7-certificates"),
        "p7c" to listOf("application/pkcs7-mime", "application/x-pkcs7-mime"),
        "p7m" to listOf("application/pkcs7-mime", "application/x-pkcs7-mime"),
        "p7r" to listOf("application/x-pkcs7-certreqresp"),
        "p7s" to listOf("application/pkcs7-signature"),
        "p8" to listOf("application/pkcs8"),
        "part" to listOf("application/pro_eng"),
        "pas" to listOf("text/x-pascal"),
        "paw" to listOf("application/vnd.pawaafile"),
        "pbd" to listOf("application/vnd.powerbuilder6"),
        "pbm" to listOf("image/x-portable-bitmap"),
        "pcap" to listOf("application/vnd.tcpdump.pcap"),
        "pcf" to listOf("application/x-font-pcf"),
        "pcl" to listOf("application/vnd.hp-pcl", "application/x-pcl"),
        "pclxl" to listOf("application/vnd.hp-pclxl"),
        "pct" to listOf("image/x-pict"),
        "pcurl" to listOf("application/vnd.curl.pcurl"),
        "pcx" to listOf("image/x-pcx"),
        "pdb" to listOf("application/vnd.palm"),
        "pdf" to listOf("application/pdf"),
        "pfa" to listOf("application/x-font-type1"),
        "pfb" to listOf("application/x-font-type1"),
        "pfm" to listOf("application/x-font-type1"),
        "pfr" to listOf("application/font-tdpfr"),
        "pfunk" to listOf("audio/make"),
        "pfx" to listOf("application/x-pkcs12"),
        "pgm" to listOf("image/x-portable-graymap"),
        "pgn" to listOf("application/x-chess-pgn"),
        "pgp" to listOf("application/pgp-encrypted"),
        "php" to listOf("text/x-php"),
        "pic" to listOf("image/x-pict"),
        "pict" to listOf("image/pict"),
        "pkg" to listOf("application/octet-stream"),
        "pki" to listOf("application/pkixcmp"),
        "pkipath" to listOf("application/pkix-pkipath"),
        "pko" to listOf("application/vnd.ms-pki.pko"),
        "pl" to listOf("text/plain", "text/x-script.perl"),
        "plb" to listOf("application/vnd.3gpp.pic-bw-large"),
        "plc" to listOf("application/vnd.mobius.plc"),
        "plf" to listOf("application/vnd.pocketlearn"),
        "pls" to listOf("application/pls+xml"),
        "plx" to listOf("application/x-pixclscript"),
        "pm" to listOf("image/x-xpixmap", "text/x-script.perl-module"),
        "pm4" to listOf("application/x-pagemaker"),
        "pm5" to listOf("application/x-pagemaker"),
        "pml" to listOf("application/vnd.ctc-posml"),
        "png" to listOf("image/png"),
        "pnm" to listOf("application/x-portable-anymap", "image/x-portable-anymap"),
        "portpkg" to listOf("application/vnd.macports.portpkg"),
        "pot" to listOf("application/mspowerpoint", "application/vnd.ms-powerpoint"),
        "potm" to listOf("application/vnd.ms-powerpoint.template.macroenabled.12"),
        "potx" to listOf("application/vnd.openxmlformats-officedocument.presentationml.template"),
        "pov" to listOf("model/x-pov"),
        "ppa" to listOf("application/vnd.ms-powerpoint"),
        "ppam" to listOf("application/vnd.ms-powerpoint.addin.macroenabled.12"),
        "ppd" to listOf("application/vnd.cups-ppd"),
        "ppm" to listOf("image/x-portable-pixmap"),
        "pps" to listOf("application/mspowerpoint", "application/vnd.ms-powerpoint"),
        "ppsm" to listOf("application/vnd.ms-powerpoint.slideshow.macroenabled.12"),
        "ppsx" to listOf("application/vnd.openxmlformats-officedocument.presentationml.slideshow"),
        "ppt" to listOf(
            "application/mspowerpoint",
            "application/powerpoint",
            "application/vnd.ms-powerpoint",
            "application/x-mspowerpoint"
        ),
        "pptm" to listOf("application/vnd.ms-powerpoint.presentation.macroenabled.12"),
        "pptx" to listOf(
            "application/vnd.openxmlformats-officedocument.presentationml.presentation"
        ),
        "ppz" to listOf("application/mspowerpoint"),
        "pqa" to listOf("application/vnd.palm"),
        "prc" to listOf("application/x-mobipocket-ebook"),
        "pre" to listOf("application/vnd.lotus-freelance"),
        "prf" to listOf("application/pics-rules"),
        "prt" to listOf("application/pro_eng"),
        "ps" to listOf("application/postscript"),
        "psb" to listOf("application/vnd.3gpp.pic-bw-small"),
        "psd" to listOf("image/vnd.adobe.photoshop"),
        "psf" to listOf("application/x-font-linux-psf"),
        "pskcxml" to listOf("application/pskc+xml"),
        "ptid" to listOf("application/vnd.pvi.ptid1"),
        "pub" to listOf("application/x-mspublisher"),
        "pvb" to listOf("application/vnd.3gpp.pic-bw-var"),
        "pvu" to listOf("paleovu/x-pv"),
        "pwn" to listOf("application/vnd.3m.post-it-notes"),
        "pwz" to listOf("application/vnd.ms-powerpoint"),
        "py" to listOf("text/x-script.phyton"),
        "pya" to listOf("audio/vnd.ms-playready.media.pya"),
        "pyc" to listOf("applicaiton/x-bytecode.python"),
        "pyo" to listOf("application/x-python-code"),
        "pyv" to listOf("video/vnd.ms-playready.media.pyv"),
        "qam" to listOf("application/vnd.epson.quickanime"),
        "qbo" to listOf("application/vnd.intu.qbo"),
        "qcp" to listOf("audio/vnd.qcelp"),
        "qd3" to listOf("x-world/x-3dmf"),
        "qd3d" to listOf("x-world/x-3dmf"),
        "qfx" to listOf("application/vnd.intu.qfx"),
        "qif" to listOf("image/x-quicktime"),
        "qps" to listOf("application/vnd.publishare-delta-tree"),
        "qt" to listOf("video/quicktime"),
        "qtc" to listOf("video/x-qtc"),
        "qti" to listOf("image/x-quicktime"),
        "qtif" to listOf("image/x-quicktime"),
        "qwd" to listOf("application/vnd.quark.quarkxpress"),
        "qwt" to listOf("application/vnd.quark.quarkxpress"),
        "qxb" to listOf("application/vnd.quark.quarkxpress"),
        "qxd" to listOf("application/vnd.quark.quarkxpress"),
        "qxl" to listOf("application/vnd.quark.quarkxpress"),
        "qxt" to listOf("application/vnd.quark.quarkxpress"),
        "ra" to listOf("audio/x-pn-realaudio", "audio/x-pn-realaudio-plugin", "audio/x-realaudio"),
        "ram" to listOf("audio/x-pn-realaudio"),
        "rar" to listOf("application/x-rar-compressed"),
        "ras" to listOf("application/x-cmu-raster", "image/cmu-raster", "image/x-cmu-raster"),
        "rast" to listOf("image/cmu-raster"),
        "rcprofile" to listOf("application/vnd.ipunplugged.rcprofile"),
        "rdf" to listOf("application/rdf+xml"),
        "rdz" to listOf("application/vnd.data-vision.rdz"),
        "rep" to listOf("application/vnd.businessobjects"),
        "res" to listOf("application/x-dtbresource+xml"),
        "rexx" to listOf("text/x-script.rexx"),
        "rf" to listOf("image/vnd.rn-realflash"),
        "rgb" to listOf("image/x-rgb"),
        "rif" to listOf("application/reginfo+xml"),
        "rip" to listOf("audio/vnd.rip"),
        "ris" to listOf("application/x-research-info-systems"),
        "rl" to listOf("application/resource-lists+xml"),
        "rlc" to listOf("image/vnd.fujixerox.edmics-rlc"),
        "rld" to listOf("application/resource-lists-diff+xml"),
        "rm" to listOf("application/vnd.rn-realmedia", "audio/x-pn-realaudio"),
        "rmi" to listOf("audio/midi"),
        "rmm" to listOf("audio/x-pn-realaudio"),
        "rmp" to listOf("audio/x-pn-realaudio", "audio/x-pn-realaudio-plugin"),
        "rms" to listOf("application/vnd.jcp.javame.midlet-rms"),
        "rmvb" to listOf("application/vnd.rn-realmedia-vbr"),
        "rnc" to listOf("application/relax-ng-compact-syntax"),
        "rng" to listOf("application/ringing-tones", "application/vnd.nokia.ringing-tone"),
        "rnx" to listOf("application/vnd.rn-realplayer"),
        "roa" to listOf("application/rpki-roa"),
        "roff" to listOf("text/troff"),
        "rp" to listOf("image/vnd.rn-realpix"),
        "rp9" to listOf("application/vnd.cloanto.rp9"),
        "rpm" to listOf("audio/x-pn-realaudio-plugin"),
        "rpss" to listOf("application/vnd.nokia.radio-presets"),
        "rpst" to listOf("application/vnd.nokia.radio-preset"),
        "rq" to listOf("application/sparql-query"),
        "rs" to listOf("application/rls-services+xml"),
        "rsd" to listOf("application/rsd+xml"),
        "rss" to listOf("application/rss+xml"),
        "rt" to listOf("text/richtext", "text/vnd.rn-realtext"),
        "rtf" to listOf("application/rtf", "application/x-rtf", "text/richtext"),
        "rtx" to listOf("application/rtf", "text/richtext"),
        "rv" to listOf("video/vnd.rn-realvideo"),
        "s" to listOf("text/x-asm"),
        "s3m" to listOf("audio/s3m"),
        "saf" to listOf("application/vnd.yamaha.smaf-audio"),
        "saveme" to listOf("aapplication/octet-stream"),
        "sbk" to listOf("application/x-tbook"),
        "sbml" to listOf("application/sbml+xml"),
        "sc" to listOf("application/vnd.ibm.secure-container"),
        "scd" to listOf("application/x-msschedule"),
        "scm" to listOf(
            "application/x-lotusscreencam",
            "text/x-script.guile",
            "text/x-script.scheme",
            "video/x-scm"
        ),
        "scq" to listOf("application/scvp-cv-request"),
        "scs" to listOf("application/scvp-cv-response"),
        "scurl" to listOf("text/vnd.curl.scurl"),
        "sda" to listOf("application/vnd.stardivision.draw"),
        "sdc" to listOf("application/vnd.stardivision.calc"),
        "sdd" to listOf("application/vnd.stardivision.impress"),
        "sdkd" to listOf("application/vnd.solent.sdkm+xml"),
        "sdkm" to listOf("application/vnd.solent.sdkm+xml"),
        "sdml" to listOf("text/plain"),
        "sdp" to listOf("application/sdp", "application/x-sdp"),
        "sdr" to listOf("application/sounder"),
        "sdw" to listOf("application/vnd.stardivision.writer"),
        "sea" to listOf("application/sea", "application/x-sea"),
        "see" to listOf("application/vnd.seemail"),
        "seed" to listOf("application/vnd.fdsn.seed"),
        "sema" to listOf("application/vnd.sema"),
        "semd" to listOf("application/vnd.semd"),
        "semf" to listOf("application/vnd.semf"),
        "ser" to listOf("application/java-serialized-object"),
        "set" to listOf("application/set"),
        "setpay" to listOf("application/set-payment-initiation"),
        "setreg" to listOf("application/set-registration-initiation"),
        "sfd-hdstx" to listOf("application/vnd.hydrostatix.sof-data"),
        "sfs" to listOf("application/vnd.spotfire.sfs"),
        "sfv" to listOf("text/x-sfv"),
        "sgi" to listOf("image/sgi"),
        "sgl" to listOf("application/vnd.stardivision.writer-global"),
        "sgm" to listOf("text/sgml", "text/x-sgml"),
        "sgml" to listOf("text/sgml", "text/x-sgml"),
        "sh" to listOf(
            "application/x-bsh",
            "application/x-sh",
            "application/x-shar",
            "text/x-script.sh"
        ),
        "shar" to listOf("application/x-bsh", "application/x-shar"),
        "shf" to listOf("application/shf+xml"),
        "shtml" to listOf("text/html", "text/x-server-parsed-html"),
        "si" to listOf("text/vnd.wap.si"),
        "sic" to listOf("application/vnd.wap.sic"),
        "sid" to listOf("image/x-mrsid-image"),
        "sig" to listOf("application/pgp-signature"),
        "sil" to listOf("audio/silk"),
        "silo" to listOf("model/mesh"),
        "sis" to listOf("application/vnd.symbian.install"),
        "sisx" to listOf("application/vnd.symbian.install"),
        "sit" to listOf("application/x-sit", "application/x-stuffit"),
        "sitx" to listOf("application/x-stuffitx"),
        "skd" to listOf("application/vnd.koan"),
        "skm" to listOf("application/vnd.koan"),
        "skp" to listOf("application/vnd.koan"),
        "skt" to listOf("application/vnd.koan"),
        "sl" to listOf("application/x-seelogo"),
        "slc" to listOf("application/vnd.wap.slc"),
        "sldm" to listOf("application/vnd.ms-powerpoint.slide.macroenabled.12"),
        "sldx" to listOf("application/vnd.openxmlformats-officedocument.presentationml.slide"),
        "slt" to listOf("application/vnd.epson.salt"),
        "sm" to listOf("application/vnd.stepmania.stepchart"),
        "smf" to listOf("application/vnd.stardivision.math"),
        "smi" to listOf("application/smil+xml"),
        "smil" to listOf("application/smil+xml"),
        "smv" to listOf("video/x-smv"),
        "smzip" to listOf("application/vnd.stepmania.package"),
        "snd" to listOf("audio/basic", "audio/x-adpcm"),
        "snf" to listOf("application/x-font-snf"),
        "so" to listOf("application/octet-stream"),
        "sol" to listOf("application/solids"),
        "spc" to listOf("application/x-pkcs7-certificates", "text/x-speech"),
        "spf" to listOf("application/vnd.yamaha.smaf-phrase"),
        "spl" to listOf("application/x-futuresplash"),
        "spot" to listOf("text/vnd.in3d.spot"),
        "spp" to listOf("application/scvp-vp-response"),
        "spq" to listOf("application/scvp-vp-request"),
        "spr" to listOf("application/x-sprite"),
        "sprite" to listOf("application/x-sprite"),
        "spx" to listOf("audio/ogg"),
        "sql" to listOf("application/x-sql"),
        "src" to listOf("application/x-wais-source"),
        "srt" to listOf("application/x-subrip"),
        "sru" to listOf("application/sru+xml"),
        "srx" to listOf("application/sparql-results+xml"),
        "ssdl" to listOf("application/ssdl+xml"),
        "sse" to listOf("application/vnd.kodak-descriptor"),
        "ssf" to listOf("application/vnd.epson.ssf"),
        "ssi" to listOf("text/x-server-parsed-html"),
        "ssm" to listOf("application/streamingmedia"),
        "ssml" to listOf("application/ssml+xml"),
        "sst" to listOf("application/vnd.ms-pki.certstore"),
        "st" to listOf("application/vnd.sailingtracker.track"),
        "stc" to listOf("application/vnd.sun.xml.calc.template"),
        "std" to listOf("application/vnd.sun.xml.draw.template"),
        "step" to listOf("application/step"),
        "stf" to listOf("application/vnd.wt.stf"),
        "sti" to listOf("application/vnd.sun.xml.impress.template"),
        "stk" to listOf("application/hyperstudio"),
        "stl" to listOf("application/sla", "application/vnd.ms-pki.stl", "application/x-navistyle"),
        "stp" to listOf("application/step"),
        "str" to listOf("application/vnd.pg.format"),
        "stw" to listOf("application/vnd.sun.xml.writer.template"),
        "sub" to listOf("text/vnd.dvb.subtitle"),
        "sus" to listOf("application/vnd.sus-calendar"),
        "susp" to listOf("application/vnd.sus-calendar"),
        "sv4cpio" to listOf("application/x-sv4cpio"),
        "sv4crc" to listOf("application/x-sv4crc"),
        "svc" to listOf("application/vnd.dvb.service"),
        "svd" to listOf("application/vnd.svd"),
        "svf" to listOf("image/vnd.dwg", "image/x-dwg"),
        "svg" to listOf("image/svg+xml"),
        "svgz" to listOf("image/svg+xml"),
        "svr" to listOf("application/x-world", "x-world/x-svr"),
        "swa" to listOf("application/x-director"),
        "swf" to listOf("application/x-shockwave-flash"),
        "swi" to listOf("application/vnd.aristanetworks.swi"),
        "sxc" to listOf("application/vnd.sun.xml.calc"),
        "sxd" to listOf("application/vnd.sun.xml.draw"),
        "sxg" to listOf("application/vnd.sun.xml.writer.global"),
        "sxi" to listOf("application/vnd.sun.xml.impress"),
        "sxm" to listOf("application/vnd.sun.xml.math"),
        "sxw" to listOf("application/vnd.sun.xml.writer"),
        "t" to listOf("text/troff"),
        "t3" to listOf("application/x-t3vm-image"),
        "taglet" to listOf("application/vnd.mynfc"),
        "talk" to listOf("text/x-speech"),
        "tao" to listOf("application/vnd.tao.intent-module-archive"),
        "tar" to listOf("application/x-tar"),
        "tbk" to listOf("application/toolbook", "application/x-tbook"),
        "tcap" to listOf("application/vnd.3gpp2.tcap"),
        "tcl" to listOf("application/x-tcl", "text/x-script.tcl"),
        "tcsh" to listOf("text/x-script.tcsh"),
        "teacher" to listOf("application/vnd.smart.teacher"),
        "tei" to listOf("application/tei+xml"),
        "teicorpus" to listOf("application/tei+xml"),
        "tex" to listOf("application/x-tex"),
        "texi" to listOf("application/x-texinfo"),
        "texinfo" to listOf("application/x-texinfo"),
        "text" to listOf("application/plain", "text/plain"),
        "tfi" to listOf("application/thraud+xml"),
        "tfm" to listOf("application/x-tex-tfm"),
        "tga" to listOf("image/x-tga"),
        "tgz" to listOf("application/gnutar", "application/x-compressed"),
        "thmx" to listOf("application/vnd.ms-officetheme"),
        "tif" to listOf("image/tiff", "image/x-tiff"),
        "tiff" to listOf("image/tiff", "image/x-tiff"),
        "tmo" to listOf("application/vnd.tmobile-livetv"),
        "torrent" to listOf("application/x-bittorrent"),
        "tpl" to listOf("application/vnd.groove-tool-template"),
        "tpt" to listOf("application/vnd.trid.tpt"),
        "tr" to listOf("text/troff"),
        "tra" to listOf("application/vnd.trueapp"),
        "trm" to listOf("application/x-msterminal"),
        "ts" to listOf("video/MP2T"),
        "tsd" to listOf("application/timestamped-data"),
        "tsi" to listOf("audio/tsp-audio"),
        "tsp" to listOf("application/dsptype", "audio/tsplayer"),
        "tsv" to listOf("text/tab-separated-values"),
        "ttc" to listOf("application/x-font-ttf"),
        "ttf" to listOf("application/x-font-ttf"),
        "ttl" to listOf("text/turtle"),
        "turbot" to listOf("image/florian"),
        "twd" to listOf("application/vnd.simtech-mindmapper"),
        "twds" to listOf("application/vnd.simtech-mindmapper"),
        "txd" to listOf("application/vnd.genomatix.tuxedo"),
        "txf" to listOf("application/vnd.mobius.txf"),
        "txt" to listOf("text/plain"),
        "u32" to listOf("application/x-authorware-bin"),
        "udeb" to listOf("application/x-debian-package"),
        "ufd" to listOf("application/vnd.ufdl"),
        "ufdl" to listOf("application/vnd.ufdl"),
        "uil" to listOf("text/x-uil"),
        "ulx" to listOf("application/x-glulx"),
        "umj" to listOf("application/vnd.umajin"),
        "uni" to listOf("text/uri-list"),
        "unis" to listOf("text/uri-list"),
        "unityweb" to listOf("application/vnd.unity"),
        "unv" to listOf("application/i-deas"),
        "uoml" to listOf("application/vnd.uoml+xml"),
        "uri" to listOf("text/uri-list"),
        "uris" to listOf("text/uri-list"),
        "urls" to listOf("text/uri-list"),
        "ustar" to listOf("application/x-ustar", "multipart/x-ustar"),
        "utz" to listOf("application/vnd.uiq.theme"),
        "uu" to listOf("application/octet-stream", "text/x-uuencode"),
        "uue" to listOf("text/x-uuencode"),
        "uva" to listOf("audio/vnd.dece.audio"),
        "uvd" to listOf("application/vnd.dece.data"),
        "uvf" to listOf("application/vnd.dece.data"),
        "uvg" to listOf("image/vnd.dece.graphic"),
        "uvh" to listOf("video/vnd.dece.hd"),
        "uvi" to listOf("image/vnd.dece.graphic"),
        "uvm" to listOf("video/vnd.dece.mobile"),
        "uvp" to listOf("video/vnd.dece.pd"),
        "uvs" to listOf("video/vnd.dece.sd"),
        "uvt" to listOf("application/vnd.dece.ttml+xml"),
        "uvu" to listOf("video/vnd.uvvu.mp4"),
        "uvv" to listOf("video/vnd.dece.video"),
        "uvva" to listOf("audio/vnd.dece.audio"),
        "uvvd" to listOf("application/vnd.dece.data"),
        "uvvf" to listOf("application/vnd.dece.data"),
        "uvvg" to listOf("image/vnd.dece.graphic"),
        "uvvh" to listOf("video/vnd.dece.hd"),
        "uvvi" to listOf("image/vnd.dece.graphic"),
        "uvvm" to listOf("video/vnd.dece.mobile"),
        "uvvp" to listOf("video/vnd.dece.pd"),
        "uvvs" to listOf("video/vnd.dece.sd"),
        "uvvt" to listOf("application/vnd.dece.ttml+xml"),
        "uvvu" to listOf("video/vnd.uvvu.mp4"),
        "uvvv" to listOf("video/vnd.dece.video"),
        "uvvx" to listOf("application/vnd.dece.unspecified"),
        "uvvz" to listOf("application/vnd.dece.zip"),
        "uvx" to listOf("application/vnd.dece.unspecified"),
        "uvz" to listOf("application/vnd.dece.zip"),
        "vcard" to listOf("text/vcard"),
        "vcd" to listOf("application/x-cdlink"),
        "vcf" to listOf("text/x-vcard"),
        "vcg" to listOf("application/vnd.groove-vcard"),
        "vcs" to listOf("text/x-vcalendar"),
        "vcx" to listOf("application/vnd.vcx"),
        "vda" to listOf("application/vda"),
        "vdo" to listOf("video/vdo"),
        "vew" to listOf("application/groupwise"),
        "vis" to listOf("application/vnd.visionary"),
        "viv" to listOf("video/vivo", "video/vnd.vivo"),
        "vivo" to listOf("video/vivo", "video/vnd.vivo"),
        "vmd" to listOf("application/vocaltec-media-desc"),
        "vmf" to listOf("application/vocaltec-media-file"),
        "vob" to listOf("video/x-ms-vob"),
        "voc" to listOf("audio/voc", "audio/x-voc"),
        "vor" to listOf("application/vnd.stardivision.writer"),
        "vos" to listOf("video/vosaic"),
        "vox" to listOf("application/x-authorware-bin"),
        "vqe" to listOf("audio/x-twinvq-plugin"),
        "vqf" to listOf("audio/x-twinvq"),
        "vql" to listOf("audio/x-twinvq-plugin"),
        "vrml" to listOf("application/x-vrml", "model/vrml", "x-world/x-vrml"),
        "vrt" to listOf("x-world/x-vrt"),
        "vsd" to listOf("application/vnd.visio"),
        "vsf" to listOf("application/vnd.vsf"),
        "vss" to listOf("application/vnd.visio"),
        "vst" to listOf("application/vnd.visio"),
        "vsw" to listOf("application/vnd.visio"),
        "vtt" to listOf("text/vtt"),
        "vtu" to listOf("model/vnd.vtu"),
        "vxml" to listOf("application/voicexml+xml"),
        "w3d" to listOf("application/x-director"),
        "w60" to listOf("application/wordperfect6.0"),
        "w61" to listOf("application/wordperfect6.1"),
        "w6w" to listOf("application/msword"),
        "wad" to listOf("application/x-doom"),
        "wav" to listOf("audio/wav", "audio/x-wav"),
        "wax" to listOf("audio/x-ms-wax"),
        "wb1" to listOf("application/x-qpro"),
        "wbmp" to listOf("image/vnd.wap.wbmp"),
        "wbs" to listOf("application/vnd.criticaltools.wbs+xml"),
        "wbxml" to listOf("application/vnd.wap.wbxml"),
        "wcm" to listOf("application/vnd.ms-works"),
        "wdb" to listOf("application/vnd.ms-works"),
        "wdp" to listOf("image/vnd.ms-photo"),
        "web" to listOf("application/vnd.xara"),
        "weba" to listOf("audio/webm"),
        "webapp" to listOf("application/x-web-app-manifest+json"),
        "webm" to listOf("video/webm"),
        "webp" to listOf("image/webp"),
        "wg" to listOf("application/vnd.pmi.widget"),
        "wgt" to listOf("application/widget"),
        "wiz" to listOf("application/msword"),
        "wk1" to listOf("application/x-123"),
        "wks" to listOf("application/vnd.ms-works"),
        "wm" to listOf("video/x-ms-wm"),
        "wma" to listOf("audio/x-ms-wma"),
        "wmd" to listOf("application/x-ms-wmd"),
        "wmf" to listOf("application/x-msmetafile"),
        "wml" to listOf("text/vnd.wap.wml"),
        "wmlc" to listOf("application/vnd.wap.wmlc"),
        "wmls" to listOf("text/vnd.wap.wmlscript"),
        "wmlsc" to listOf("application/vnd.wap.wmlscriptc"),
        "wmv" to listOf("video/x-ms-wmv"),
        "wmx" to listOf("video/x-ms-wmx"),
        "wmz" to listOf("application/x-msmetafile"),
        "woff" to listOf("application/x-font-woff"),
        "word" to listOf("application/msword"),
        "wp" to listOf("application/wordperfect"),
        "wp5" to listOf("application/wordperfect", "application/wordperfect6.0"),
        "wp6" to listOf("application/wordperfect"),
        "wpd" to listOf("application/wordperfect", "application/x-wpwin"),
        "wpl" to listOf("application/vnd.ms-wpl"),
        "wps" to listOf("application/vnd.ms-works"),
        "wq1" to listOf("application/x-lotus"),
        "wqd" to listOf("application/vnd.wqd"),
        "wri" to listOf("application/mswrite", "application/x-wri"),
        "wrl" to listOf("application/x-world", "model/vrml", "x-world/x-vrml"),
        "wrz" to listOf("model/vrml", "x-world/x-vrml"),
        "wsc" to listOf("text/scriplet"),
        "wsdl" to listOf("application/wsdl+xml"),
        "wspolicy" to listOf("application/wspolicy+xml"),
        "wsrc" to listOf("application/x-wais-source"),
        "wtb" to listOf("application/vnd.webturbo"),
        "wtk" to listOf("application/x-wintalk"),
        "wvx" to listOf("video/x-ms-wvx"),
        "x-png" to listOf("image/png"),
        "x32" to listOf("application/x-authorware-bin"),
        "x3d" to listOf("model/x3d+xml"),
        "x3db" to listOf("model/x3d+binary"),
        "x3dbz" to listOf("model/x3d+binary"),
        "x3dv" to listOf("model/x3d+vrml"),
        "x3dvz" to listOf("model/x3d+vrml"),
        "x3dz" to listOf("model/x3d+xml"),
        "xaml" to listOf("application/xaml+xml"),
        "xap" to listOf("application/x-silverlight-app"),
        "xar" to listOf("application/vnd.xara"),
        "xbap" to listOf("application/x-ms-xbap"),
        "xbd" to listOf("application/vnd.fujixerox.docuworks.binder"),
        "xbm" to listOf("image/x-xbitmap", "image/x-xbm", "image/xbm"),
        "xdf" to listOf("application/xcap-diff+xml"),
        "xdm" to listOf("application/vnd.syncml.dm+xml"),
        "xdp" to listOf("application/vnd.adobe.xdp+xml"),
        "xdr" to listOf("video/x-amt-demorun"),
        "xdssc" to listOf("application/dssc+xml"),
        "xdw" to listOf("application/vnd.fujixerox.docuworks"),
        "xenc" to listOf("application/xenc+xml"),
        "xer" to listOf("application/patch-ops-error+xml"),
        "xfdf" to listOf("application/vnd.adobe.xfdf"),
        "xfdl" to listOf("application/vnd.xfdl"),
        "xgz" to listOf("xgl/drawing"),
        "xht" to listOf("application/xhtml+xml"),
        "xhtml" to listOf("application/xhtml+xml"),
        "xhvml" to listOf("application/xv+xml"),
        "xif" to listOf("image/vnd.xiff"),
        "xl" to listOf("application/excel"),
        "xla" to listOf("application/excel", "application/x-excel", "application/x-msexcel"),
        "xlam" to listOf("application/vnd.ms-excel.addin.macroenabled.12"),
        "xlb" to listOf("application/excel", "application/vnd.ms-excel", "application/x-excel"),
        "xlc" to listOf("application/excel", "application/vnd.ms-excel", "application/x-excel"),
        "xld" to listOf("application/excel", "application/x-excel"),
        "xlf" to listOf("application/x-xliff+xml"),
        "xlk" to listOf("application/excel", "application/x-excel"),
        "xll" to listOf("application/excel", "application/vnd.ms-excel", "application/x-excel"),
        "xlm" to listOf("application/excel", "application/vnd.ms-excel", "application/x-excel"),
        "xls" to listOf(
            "application/excel",
            "application/vnd.ms-excel",
            "application/x-excel",
            "application/x-msexcel"
        ),
        "xlsb" to listOf("application/vnd.ms-excel.sheet.binary.macroenabled.12"),
        "xlsm" to listOf("application/vnd.ms-excel.sheet.macroenabled.12"),
        "xlsx" to listOf("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
        "xlt" to listOf("application/excel", "application/x-excel"),
        "xltm" to listOf("application/vnd.ms-excel.template.macroenabled.12"),
        "xltx" to listOf("application/vnd.openxmlformats-officedocument.spreadsheetml.template"),
        "xlv" to listOf("application/excel", "application/x-excel"),
        "xlw" to listOf(
            "application/excel",
            "application/vnd.ms-excel",
            "application/x-excel",
            "application/x-msexcel"
        ),
        "xm" to listOf("audio/xm"),
        "xml" to listOf("application/xml", "text/xml"),
        "xmz" to listOf("xgl/movie"),
        "xo" to listOf("application/vnd.olpc-sugar"),
        "xop" to listOf("application/xop+xml"),
        "xpdl" to listOf("application/xml"),
        "xpi" to listOf("application/x-xpinstall"),
        "xpix" to listOf("application/x-vnd.ls-xpix"),
        "xpl" to listOf("application/xproc+xml"),
        "xpm" to listOf("image/x-xpixmap", "image/xpm"),
        "xpr" to listOf("application/vnd.is-xpr"),
        "xps" to listOf("application/vnd.ms-xpsdocument"),
        "xpw" to listOf("application/vnd.intercon.formnet"),
        "xpx" to listOf("application/vnd.intercon.formnet"),
        "xsl" to listOf("application/xml"),
        "xslt" to listOf("application/xslt+xml"),
        "xsm" to listOf("application/vnd.syncml+xml"),
        "xspf" to listOf("application/xspf+xml"),
        "xsr" to listOf("video/x-amt-showrun"),
        "xul" to listOf("application/vnd.mozilla.xul+xml"),
        "xvm" to listOf("application/xv+xml"),
        "xvml" to listOf("application/xv+xml"),
        "xwd" to listOf("image/x-xwd", "image/x-xwindowdump"),
        "xyz" to listOf("chemical/x-xyz"),
        "xz" to listOf("application/x-xz"),
        "yang" to listOf("application/yang"),
        "yin" to listOf("application/yin+xml"),
        "z" to listOf("application/x-compress", "application/x-compressed"),
        "z1" to listOf("application/x-zmachine"),
        "z2" to listOf("application/x-zmachine"),
        "z3" to listOf("application/x-zmachine"),
        "z4" to listOf("application/x-zmachine"),
        "z5" to listOf("application/x-zmachine"),
        "z6" to listOf("application/x-zmachine"),
        "z7" to listOf("application/x-zmachine"),
        "z8" to listOf("application/x-zmachine"),
        "zaz" to listOf("application/vnd.zzazz.deck+xml"),
        "zip" to listOf(
            "application/x-compressed",
            "application/x-zip-compressed",
            "application/zip",
            "multipart/x-zip"
        ),
        "zir" to listOf("application/vnd.zul"),
        "zirz" to listOf("application/vnd.zul"),
        "zmm" to listOf("application/vnd.handheld-entertainment+xml"),
        "zoo" to listOf("application/octet-stream"),
        "zsh" to listOf("text/x-script.zsh"),
        "123" to listOf("application/vnd.lotus-1-2-3")
    )

    fun guessMimeTypeFromExtension(extension: String?): String? {
        val correctedExtension = extension?.lowercase()

        return mimeTypeMap[correctedExtension]?.first()
    }
}
